# Generated by Django 3.1.4 on 2020-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=25)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('iva', models.IntegerField(blank=True, default=12, null=True)),
                ('indice', models.IntegerField(blank=True, default=25, null=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresa',
                'ordering': ['-nombre', '-ruc', '-direccion'],
            },
        ),
    ]
