# Generated by Django 3.1.4 on 2020-12-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('tipo_doc', models.IntegerField(choices=[(1, 'CEDULA'), (0, 'RUC')], default=1)),
                ('numero_doc', models.CharField(max_length=13, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedor',
                'ordering': ['-nombres', '-numero_doc'],
            },
        ),
    ]
