# Generated by Django 3.1.4 on 2021-01-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='empresa',
        ),
    ]
