# Generated by Django 3.1.4 on 2021-03-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
