# Generated by Django 3.1.4 on 2020-12-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_inventario'),
        ('venta', '0003_detalle_venta_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta'),
        ),
    ]
