# Generated by Django 3.1.4 on 2021-01-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_inventario_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='select',
        ),
    ]
