# Generated by Django 3.1.4 on 2021-04-01 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
        ('inventario', '0006_remove_inventario_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubicacion.ubicacion'),
        ),
    ]
