# Generated by Django 3.1.4 on 2021-05-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_inventario_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='venta',
        ),
    ]
