# Generated by Django 3.1.4 on 2020-12-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_delete_inventario'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Detalle_venta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
