# Generated by Django 3.1.4 on 2021-01-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_detalle_venta_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='cantidadp',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='pvp_actual',
            new_name='pvp',
        ),
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='subtotalp',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='cantidads',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='pvp_actual_s',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='subtotals',
        ),
    ]
