# Generated by Django 3.1.4 on 2021-01-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20210107_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='empleado',
        ),
    ]
