# Generated by Django 3.1.4 on 2021-01-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_remove_venta_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='p_venta_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
