# Generated by Django 3.1.4 on 2021-01-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='p_compra_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
