# Generated by Django 3.1.4 on 2021-03-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_detalle_compra_p_compra_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='inventario_estado',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=1),
        ),
    ]
